version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    rebase-strategy: disabled
    reviewers:
      - mmyoji
    ignore:
      - dependency-name: "@types/node"
        versions: ["17.x"]
